import React, {
  useCallback,
  useEffect,
  useImperativeHandle,
  useState,
} from 'react';
import type { Editor } from '@tiptap/core';
import katex from 'katex';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { Calculator } from 'lucide-react';

export interface MathPopoverHandle {
  openForEdit(latex: string, isBlock: boolean, pos: number): void;
  openForNew(): void;
}

interface MathPopoverProps {
  editor: Editor;
  disabled: boolean;
}

export const MathPopover = React.forwardRef<
  MathPopoverHandle,
  MathPopoverProps
>(function MathPopover({ editor, disabled }, ref) {
  const [open, setOpen] = useState(false);
  const [mathLatex, setMathLatex] = useState('');
  const [mathIsBlock, setMathIsBlock] = useState(false);
  const [mathEditingPos, setMathEditingPos] = useState<number | null>(null);
  const [mathPreview, setMathPreview] = useState('');

  const generatePreview = useCallback((latex: string, isBlock: boolean) => {
    if (!latex.trim()) {
      setMathPreview('');
      return;
    }
    try {
      const html = katex.renderToString(latex, {
        throwOnError: false,
        displayMode: isBlock,
        output: 'html',
      });
      setMathPreview(html);
    } catch {
      setMathPreview('');
    }
  }, []);

  useEffect(() => {
    generatePreview(mathLatex, mathIsBlock);
  }, [mathLatex, mathIsBlock, generatePreview]);

  useImperativeHandle(ref, () => ({
    openForEdit(latex: string, isBlock: boolean, pos: number) {
      setMathLatex(latex);
      setMathIsBlock(isBlock);
      setMathEditingPos(pos);
      generatePreview(latex, isBlock);
      setOpen(true);
    },
    openForNew() {
      setMathLatex('');
      setMathIsBlock(false);
      setMathEditingPos(null);
      setMathPreview('');
      setOpen(true);
    },
  }));

  const handleInsertMath = useCallback(() => {
    if (!mathLatex.trim()) return;

    if (mathEditingPos !== null) {
      const currentNode = editor.state.doc.nodeAt(mathEditingPos);
      const wasBlock = currentNode?.type.name === 'blockMath';

      if (wasBlock === mathIsBlock) {
        if (mathIsBlock) {
          editor
            .chain()
            .setNodeSelection(mathEditingPos)
            .updateBlockMath({ latex: mathLatex })
            .run();
        } else {
          editor
            .chain()
            .setNodeSelection(mathEditingPos)
            .updateInlineMath({ latex: mathLatex })
            .run();
        }
      } else {
        if (wasBlock) {
          editor
            .chain()
            .setNodeSelection(mathEditingPos)
            .deleteBlockMath()
            .run();
        } else {
          editor
            .chain()
            .setNodeSelection(mathEditingPos)
            .deleteInlineMath()
            .run();
        }
        if (mathIsBlock) {
          editor.chain().focus().insertBlockMath({ latex: mathLatex }).run();
        } else {
          editor.chain().focus().insertInlineMath({ latex: mathLatex }).run();
        }
      }
    } else {
      if (mathIsBlock) {
        editor.chain().focus().insertBlockMath({ latex: mathLatex }).run();
      } else {
        editor.chain().focus().insertInlineMath({ latex: mathLatex }).run();
      }
    }

    setMathLatex('');
    setMathIsBlock(false);
    setMathEditingPos(null);
    setMathPreview('');
    setOpen(false);
  }, [editor, mathLatex, mathIsBlock, mathEditingPos]);

  const handleRemoveMath = useCallback(() => {
    if (mathEditingPos === null) return;

    if (mathIsBlock) {
      editor.chain().setNodeSelection(mathEditingPos).deleteBlockMath().run();
    } else {
      editor.chain().setNodeSelection(mathEditingPos).deleteInlineMath().run();
    }

    setMathLatex('');
    setMathIsBlock(false);
    setMathEditingPos(null);
    setMathPreview('');
    setOpen(false);
  }, [editor, mathIsBlock, mathEditingPos]);

  const handleClose = useCallback(() => {
    setOpen(false);
    setMathLatex('');
    setMathIsBlock(false);
    setMathEditingPos(null);
  }, []);

  // KaTeX preview HTML is safe — generated by the KaTeX library from
  // user-supplied LaTeX, not from arbitrary HTML. KaTeX only outputs
  // math-rendering markup and never executes scripts.
  const previewHtml = mathPreview;

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          disabled={disabled}
          title="Add math formula"
          className="h-8 w-8 p-0"
          onClick={() => {
            setMathLatex('');
            setMathIsBlock(false);
            setMathEditingPos(null);
            setMathPreview('');
            setOpen(true);
          }}
        >
          <Calculator className="h-4 w-4" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-96" align="start">
        <div className="space-y-4">
          <div className="text-sm font-medium">
            {mathEditingPos !== null ? 'Edit Math Formula' : 'Add Math Formula'}
          </div>

          <div className="space-y-3">
            <div className="space-y-2">
              <Label htmlFor="math-latex">LaTeX Formula</Label>
              <Input
                id="math-latex"
                placeholder="E = mc^2, \frac{a}{b}, \sum_{i=1}^{n} i"
                value={mathLatex}
                onChange={e => setMathLatex(e.target.value)}
                onKeyDown={e => {
                  if (e.key === 'Enter' && e.ctrlKey) {
                    handleInsertMath();
                  }
                }}
              />
              <p className="text-xs text-muted-foreground">
                Use LaTeX notation. Press Ctrl+Enter to insert.
              </p>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="math-block"
                checked={mathIsBlock}
                onCheckedChange={checked => setMathIsBlock(checked === true)}
              />
              <Label htmlFor="math-block" className="text-sm">
                Block formula (displayed on its own line)
              </Label>
            </div>

            {mathLatex.trim() && (
              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">
                  Preview:
                </Label>
                <div className="p-3 border rounded-md bg-muted/50 min-h-[60px] flex items-center justify-center">
                  {previewHtml ? (
                    <div
                      className={mathIsBlock ? 'block' : 'inline'}
                      // Safe: KaTeX.renderToString produces only math markup
                      dangerouslySetInnerHTML={{
                        __html: previewHtml,
                      }}
                    />
                  ) : (
                    <div className="text-sm text-muted-foreground">
                      Invalid LaTeX syntax
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleClose}
            >
              Cancel
            </Button>
            {mathEditingPos !== null && (
              <Button
                type="button"
                variant="destructive"
                size="sm"
                onClick={handleRemoveMath}
              >
                Remove
              </Button>
            )}
            <Button
              type="button"
              size="sm"
              onClick={handleInsertMath}
              disabled={!mathLatex.trim()}
            >
              {mathEditingPos !== null ? 'Update Formula' : 'Insert Formula'}
            </Button>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
});
