import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Subject color gradients - safelist all color variants
    // Amber
    'from-amber-50',
    'to-amber-100/50',
    'dark:from-amber-950/40',
    'dark:to-amber-900/20',
    'border-amber-200/40',
    'dark:border-amber-800/30',
    'bg-amber-500/10',
    'dark:bg-amber-500/20',
    'text-amber-600',
    'dark:text-amber-400',
    'hover:bg-amber-500/10',
    'dark:hover:bg-amber-500/20',
    // Orange
    'from-orange-50',
    'to-orange-100/50',
    'dark:from-orange-950/40',
    'dark:to-orange-900/20',
    'border-orange-200/40',
    'dark:border-orange-800/30',
    'bg-orange-500/10',
    'dark:bg-orange-500/20',
    'text-orange-600',
    'dark:text-orange-400',
    'hover:bg-orange-500/10',
    'dark:hover:bg-orange-500/20',
    // Rose
    'from-rose-50',
    'to-rose-100/50',
    'dark:from-rose-950/40',
    'dark:to-rose-900/20',
    'border-rose-200/40',
    'dark:border-rose-800/30',
    'bg-rose-500/10',
    'dark:bg-rose-500/20',
    'text-rose-600',
    'dark:text-rose-400',
    'hover:bg-rose-500/10',
    'dark:hover:bg-rose-500/20',
    // Blue
    'from-blue-50',
    'to-blue-100/50',
    'dark:from-blue-950/40',
    'dark:to-blue-900/20',
    'border-blue-200/40',
    'dark:border-blue-800/30',
    'bg-blue-500/10',
    'dark:bg-blue-500/20',
    'text-blue-600',
    'dark:text-blue-400',
    'hover:bg-blue-500/10',
    'dark:hover:bg-blue-500/20',
    // Emerald
    'from-emerald-50',
    'to-emerald-100/50',
    'dark:from-emerald-950/40',
    'dark:to-emerald-900/20',
    'border-emerald-200/40',
    'dark:border-emerald-800/30',
    'bg-emerald-500/10',
    'dark:bg-emerald-500/20',
    'text-emerald-600',
    'dark:text-emerald-400',
    'hover:bg-emerald-500/10',
    'dark:hover:bg-emerald-500/20',
    // Purple
    'from-purple-50',
    'to-purple-100/50',
    'dark:from-purple-950/40',
    'dark:to-purple-900/20',
    'border-purple-200/40',
    'dark:border-purple-800/30',
    'bg-purple-500/10',
    'dark:bg-purple-500/20',
    'text-purple-600',
    'dark:text-purple-400',
    'hover:bg-purple-500/10',
    'dark:hover:bg-purple-500/20',
    // Teal
    'from-teal-50',
    'to-teal-100/50',
    'dark:from-teal-950/40',
    'dark:to-teal-900/20',
    'border-teal-200/40',
    'dark:border-teal-800/30',
    'bg-teal-500/10',
    'dark:bg-teal-500/20',
    'text-teal-600',
    'dark:text-teal-400',
    'hover:bg-teal-500/10',
    'dark:hover:bg-teal-500/20',
    // Pink
    'from-pink-50',
    'to-pink-100/50',
    'dark:from-pink-950/40',
    'dark:to-pink-900/20',
    'border-pink-200/40',
    'dark:border-pink-800/30',
    'bg-pink-500/10',
    'dark:bg-pink-500/20',
    'text-pink-600',
    'dark:text-pink-400',
    'hover:bg-pink-500/10',
    'dark:hover:bg-pink-500/20',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'collapsible-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        'collapsible-up': {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'collapsible-down': 'collapsible-down 0.2s ease-out',
        'collapsible-up': 'collapsible-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
